name: Check on PR

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  checkstyle-on-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 19
      uses: actions/setup-java@v2
      with:
        java-version: 'adopt@1.19'

    - name: Build with Maven
      run: mvn clean install

    - name: Checkstyle
      run: mvn checkstyle:check
