name: Check on PR

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check-on-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Build with Maven
        run: mvn clean install

      - name: Checkstyle
        run: mvn checkstyle:check
